apiVersion: v1
kind: Secret
metadata:
  name: secret-oauth2-proxy
type: Opaque
data:
  OAUTH2_PROXY_CLIENT_SECRET: {{ .Values.secret.clientSecret | b64enc | quote }}
  OAUTH2_PROXY_COOKIE_SECRET: {{ .Values.secret.cookieSecret | b64enc | quote }}