apiVersion: v1
kind: ConfigMap
metadata:
  name: otus-sw-arch-hw-app-config
data:
  APP_NAME: {{ .Release.Name }}
  APP_URL_SCHEME: {{ .Values.config.app_url_scheme }}
  APP_URL_HOST: {{ .Values.config.app_url_host }}
  APP_URL_PATH: {{ .Values.config.app_url_path }}
  AUTH_APP_URL_SCHEME: {{ .Values.config.auth_app_url_scheme }}
  AUTH_APP_URL_HOST: {{ .Values.config.auth_app_url_host }}
  AUTH_APP_URL_PATH: {{ .Values.config.auth_app_url_path }}
  AUTH_PUB_KEY: {{ .Values.config.auth_pub_key }}
